### ISSUE TITLE
Vox voices turn off after sailing?

### ISSUE THREAD

**Issue by ZephyrArt** [brpocock/grizzards#583] opened 2022-10-04 16:52 UTC
Happens after sailing in either direction
Does not resume when pressing reset
DOES resume after restarting the system

**Comment by ZephyrArt** [comment] 2022-10-04 16:53
This was on a Megax cheat save file

**Comment by brpocock** [comment] 2022-10-04 18:06
Duplicate of (caused by incorrect fix to) #556

**Closed by brpocock** 2022-10-04 18:06 UTC
Labels: bug
